# Site settings
title: 
header-img: img/home-bg.png
email: kristen.warnquist@gmail.com
copyright_name: kdub815
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kdub815
learn_profile: kdub815
email_username: kristen.warnquist@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
